name: Test rosbag2_bag_v2
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every 6 hours. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros@0.0.26
      with:
        required-ros-distributions: melodic
    - uses: ros-tooling/action-ros-ci@0.1.0
      with:
        package-name: ros1_rosbag_storage_vendor rosbag2_bag_v2_plugins
        source-ros-binary-installation: melodic
