name: Test rosbag2_bag_v2
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every 6 hours. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
        ros1_distro: [noetic]
        ros2_distro: [foxy]
    steps:
    - uses: ros-tooling/setup-ros@0.0.25
    - uses: ros-tooling/action-ros-ci@0.0.19
      with:
        package-name: ros1_rosbag_storage_vendor rosbag2_bag_v2_plugins
        target-ros1-distro: ${{ matrix.ros1_distro }}
        target-ros2-distro: ${{ matrix.ros2_distro }}
