name: Test rosbag2_bag_v2
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every 6 hours. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Cache ROS packages
      uses: actions/cache@v1
      env:
        cache-name: cache-ros-packages
      with:
        path: /opt/ros
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: ros-tooling/setup-ros@0.0.15
      with:
        required-ros-distributions: melodic
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: ros1_rosbag_storage_vendor rosbag2_bag_v2_plugins
        source-ros-binary-installation: melodic
