name: Test rosbag2_bag_v2
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every 6 hours. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros@0.0.15
      with:
        required-ros-distributions: melodic
    # ros-melodic-desktop uninstalls python3-catkin-pkg due to a package conflict with
    # python-catkin-pkg. We need to reinstall it in order for colcon to work.
    # See https://answers.ros.org/question/345875/installing-ros-melodic-desktop-uninstalls-python3-catkin-pkg/
    - name: Install catkin-pkg
      run: |
        sudo apt install -y python3-catkin-pkg-modules
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: ros1_rosbag_storage_vendor rosbag2_bag_v2_plugins
        source-ros-binary-installation: melodic
